### ISSUE TITLE
How to get bosecontrol(.c) to work?

### ISSUE THREAD

**Issue by hepcat72** [probonopd/Lifestyle#4]
I was able to successfully test `cat mute.json > /dev/udp/127.0.0.1/12345` with pi-rc, which continually mutes and unmutes my Bose system.

I compiled bosecontrol.c.  (There were a lot of warnings about unused variables, including all of the raw_NEC2_186_85_*.  I noted though that it appears to only be coded to send the mute signal.)

However, running `sudo ./bosecontrol -v` doesn't mute my Bose system like pi-rc did.  And I'm not sure whether I also need to be running `sudo ./pi_pcm`.  I assume not, but I tried it.

I tried writing a loop to cycle through different values for -y from -100 to 100.

I saw that you have a -100 adjustment for usleep in the for loop at the bottom that you found by trial and error.  I don't know if I should try and edit that...

If the test with pi-rc worked, shouldn't bosecontrol work without any custom adjustments?  What parameters do I need to supply to get the mute test (`raw_NEC2_186_85_1`) to work?

**Comment by probonopd** [comment]
Hi @hepcat72 welcome, glad you found this. Unfortunately I don't have access to the hardware at this time, but I have shown the tools and techniques I have used to reverse engineer this. You should be able to figure out what is going on using the same tools and techniques. Good luck!

**Comment by hepcat72** [comment]
Well, I don't have the equipment to detect the signals, so I'd like to see if you have any suggestions for the following...

I was thinking that I can loop through some values in a range for the variables I can adjust.  I'll echo the values as I try them along with a time.  I could leave it unattended and record audio with a recorder (with the bose tuned to a radio station) as I try the "off" code.  After, I could scan through the recording to find the time index where the stereo turned off and look at the verbose output to see which variable value(s) worked.  I could then refine the values manually using the mute code to find the range and select the center.

The question is which variables should I adjust, what range of values would be good to try, and how much should I increment them to be likely to not skip over the target value, but minimize the number of attempts?

I already tried adjusting -y from -100 to 100, incrementing by 1.  I noticed it is a float however, so I also tried -10 to 10, incrementing by 0.1 and I tried -1 to 1 incrementing by 0.01.  In your README, you don't mention needing to use -y.  Did you use it in your testing and if so, what value did you supply and what range did you search through?

The only other value I was thinking I could try is that `-100` that's hard-coded in the loop for the timing between bursts.  I could add an option for that and try different values for (both) it (and -y in combination).

Are there any other values I should try and manipulate?

**Comment by probonopd** [comment]
The easiest is to go the ESP8266 route I‘d say.

**Comment by hepcat72** [comment]
No doubt it'd be easier if I purchased some hardware.  I'm going to see if I can do it without extra equipment... let's say, for fun.

**Comment by probonopd** [comment]
OK. Maybe you can use your sound card as a "poor man's oscilloscope" somehow to record the pulses and compare to the original remote's pulses, then play with the values until the two match. Please don't fry your sound card in the process though...

**Comment by hepcat72** [comment]
I was messing around tonight with the code and googling some.  I saw the comment on the PLL0_FREQUENCY variable about your rev 2 processor speed.  Is this a value I should change for my hardware?  I don't know much of anything about hardware, but my RPi is version 3.  It has an armv7l processor.  I looked it up and it's supposed to be anywhere between 600Mhz to 1200Mhz.

**Comment by hepcat72** [comment]
I got my [fork of pi-rc](https://github.com/hepcat72/pi-rc) to send a single command and I created a folder of all the json files for the commands relevant to my Bose Lifestyle version.  I also configured homebridge-commander to control the stereo, so I'll close out this issue.  I might try out rpitx in the future if I can figure it out...
